apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  # AWS_CLUSTER_NAME and AWS_REGION will override `name` and `region` here.
  name: poc-embark-dl-benchmark
  region: us-east-1
  tags:
    owner: ivan.borisov
    project: embarktrucks
    jira: CSAWSCERT-241
  # version: '1.21.2'
# If your region has multiple availability zones, you can specify 3 of them.
availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]

# NodeGroup holds all configuration attributes that are specific to a nodegroup
# You can have several node group in your cluster.
nodeGroups:
  - name: training
    instanceType: p3.2xlarge
    desiredCapacity: 1
    minSize: 0
    maxSize: 2
    volumeSize: 30
    availabilityZones: ["us-east-1a"]
    iam:
      withAddonPolicies:
        efs: true
        fsx: true
